import { useQuery } from "@tanstack/react-query";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
  PieChart,
  Pie,
  Cell,
  Legend,
  BarChart,
  Bar,
} from "recharts";
import { getAnalytics } from "@/api/endpoints";
import { Card, CardContent, CardHeader, CardTitle, Loader } from "@/components/ui";
import { humanizeEvent } from "@/lib/utils";

const COLORS = ["#7c3aed", "#06b6d4", "#f59e0b", "#10b981", "#ef4444", "#8b5cf6", "#3b82f6", "#ec4899"];

export default function Analytics() {
  const { data, isLoading } = useQuery({
    queryKey: ["analytics"],
    queryFn: getAnalytics,
  });

  if (isLoading || !data) return <Loader />;

  const pieData = Object.entries(data.event_distribution).map(([key, value]) => ({
    name: humanizeEvent(key),
    value,
  }));

  const barData = [
    { name: "Documents", count: data.documents_uploaded.reduce((s, p) => s + p.count, 0) },
    { name: "Notes", count: data.notes_generated.reduce((s, p) => s + p.count, 0) },
    { name: "Flashcards", count: data.flashcards_created.reduce((s, p) => s + p.count, 0) },
    { name: "MCQs", count: data.mcqs_generated.reduce((s, p) => s + p.count, 0) },
    { name: "Chats", count: data.chat_usage.reduce((s, p) => s + p.count, 0) },
  ];

  return (
    <div className="space-y-6">
      <div>
        {/* Upgraded Header Typography */}
        <h1 className="text-3xl font-bold">Analytics</h1>
        <p className="text-sm text-muted-foreground">Visualize your usage and activity trends over time.</p>
      </div>

      {/* Document Uploads Card Container */}
      <Card className="border-white/10 bg-white/5 backdrop-blur-xl rounded-2xl p-6">
        <CardHeader className="px-0 pt-0">
          <CardTitle>Document Uploads Over Time</CardTitle>
        </CardHeader>
        <CardContent className="h-72 px-0 pb-0">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={data.documents_uploaded}>
              <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
              <XAxis dataKey="date" tick={{ fontSize: 12 }} />
              <YAxis allowDecimals={false} tick={{ fontSize: 12 }} />
              <Tooltip />
              <Line type="monotone" dataKey="count" stroke="#7c3aed" strokeWidth={2} />
            </LineChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        {/* Activity Distribution Card Container */}
        <Card className="border-white/10 bg-white/5 backdrop-blur-xl rounded-2xl p-6">
          <CardHeader className="px-0 pt-0">
            <CardTitle>Activity Distribution</CardTitle>
          </CardHeader>
          <CardContent className="h-72 px-0 pb-0">
            {pieData.length === 0 ? (
              <p className="flex h-full items-center justify-center text-sm text-muted-foreground">No activity yet.</p>
            ) : (
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={pieData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={90} label>
                    {pieData.map((_, idx) => (
                      <Cell key={idx} fill={COLORS[idx % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                  <Legend />
                </PieChart>
              </ResponsiveContainer>
            )}
          </CardContent>
        </Card>

        {/* Content Generated Card Container */}
        <Card className="border-white/10 bg-white/5 backdrop-blur-xl rounded-2xl p-6">
          <CardHeader className="px-0 pt-0">
            <CardTitle>Content Generated by Type</CardTitle>
          </CardHeader>
          <CardContent className="h-72 px-0 pb-0">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={barData}>
                <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                <XAxis dataKey="name" tick={{ fontSize: 12 }} />
                <YAxis allowDecimals={false} tick={{ fontSize: 12 }} />
                <Tooltip />
                <Bar dataKey="count" fill="#06b6d4" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        {/* Chat Usage Trend Card Container */}
        <Card className="border-white/10 bg-white/5 backdrop-blur-xl rounded-2xl p-6">
          <CardHeader className="px-0 pt-0">
            <CardTitle>Chat Usage Trend</CardTitle>
          </CardHeader>
          <CardContent className="h-64 px-0 pb-0">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={data.chat_usage}>
                <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                <XAxis dataKey="date" tick={{ fontSize: 12 }} />
                <YAxis allowDecimals={false} tick={{ fontSize: 12 }} />
                <Tooltip />
                <Line type="monotone" dataKey="count" stroke="#10b981" strokeWidth={2} />
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* MCQs Generated Trend Card Container */}
        <Card className="border-white/10 bg-white/5 backdrop-blur-xl rounded-2xl p-6">
          <CardHeader className="px-0 pt-0">
            <CardTitle>MCQs Generated Trend</CardTitle>
          </CardHeader>
          <CardContent className="h-64 px-0 pb-0">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={data.mcqs_generated}>
                <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                <XAxis dataKey="date" tick={{ fontSize: 12 }} />
                <YAxis allowDecimals={false} tick={{ fontSize: 12 }} />
                <Tooltip />
                <Line type="monotone" dataKey="count" stroke="#f59e0b" strokeWidth={2} />
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}